# Generated by Django 4.2.6 on 2024-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('Pword', models.CharField(max_length=100)),
                ('today', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
