# Generated by Django 5.0.3 on 2024-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(max_length=25)),
                ('today', models.DateField(auto_now=True)),
            ],
        ),
    ]
