# Generated by Django 5.0.3 on 2024-03-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Customer',
        ),
    ]
