# Generated by Django 5.0.3 on 2024-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_person_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Person',
        ),
        migrations.AddField(
            model_name='hire',
            name='file',
            field=models.FileField(default='default.txt', upload_to=''),
        ),
    ]
