# Generated by Django 5.0.3 on 2024-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_customer_person_hire_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
