# Generated by Django 5.0.3 on 2024-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_hire_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Pword',
        ),
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(default='', upload_to='tasks/'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
